export const COPY = {
  getTickets: 'Get tickets',
  launchDrop: 'Launch a drop',
  openSales: 'Open sales',
  fillTheRoom: 'Fill the room',
  trackDemand: 'Track demand',
  joinWaitlist: 'Join waitlist',
  notifyMe: 'Notify me',
  shareDrop: 'Share drop',
  completeOrder: 'Complete your order',
  lockTickets: 'Lock your tickets',
  doorScanner: 'Door scanner',
  myWallet: 'My Wallet',
  ticketsUnlock: 'Tickets unlock',
  onSaleNow: 'On sale',
  almostGone: 'Almost gone',
  soldOut: 'Sold out',
  saleEnded: 'Sale ended',
  secureCheckout: 'Secure checkout via Stripe',
  holdWarning: 'Your tickets are held — complete checkout before the timer runs out.',
  payNow: 'Pay now',
  commandCenter: 'Organizer hub',
  exportAttendees: 'Export CSV',
  createPromo: 'Create promo code',
  findTheDrop: 'Find the drop',
  seeWhatsLive: "See what's live",
  joinTheRoom: 'Join the room',
  launchADrop: 'Launch a drop',
  openNewDrop: 'Open a new drop',
  liveNow: 'Live now',
  sellingFast: 'Selling fast',
  beforeSale: 'Before sale',
  searchGuest: 'Search guest',
  trustSecure: 'Secure payment',
  trustInstant: 'Instant wallet',
  trustNoAccount: 'No account needed',
  nextAction: 'Next action',
  settingUpCommandCenter: 'Setting up organizer hub…',
  commandCenterAccess: 'Organizer hub access',
  organizerAccessFailed: 'Could not enable organizer access. Try again or sign in with an organizer account.',
  searchVenue: 'Search venue or address',
  searchDrops: 'Search drops, venues, rooms…',
  noVenuesFound: 'No venues found',
  addressLookupFailed: 'Address lookup unavailable',
  selectState: 'Select state',
  selectCity: 'Select city',
  signIn: 'Sign in',
  signInEmail: 'Sign in with email',
  buyTickets: 'Buy tickets',
  dropsNav: 'Drops',
  organizers: 'Organizers',
  manageDrops: 'Manage drops',
  quickLinks: 'Quick links',
  liveDropsLink: 'Live drops',
  backHome: 'Back home',
  tryAgain: 'Try again',
  dropNotFound: 'Drop not found',
  dropNotFoundHint: 'This room may have ended or the link is wrong.',
  aboutDrop: 'About the drop',
  presentedBy: 'Presented by',
  dropCurator: 'Drop curator',
  topDrop: 'Top drop',
  featuredDrop: 'Featured',
  forOrganizers: 'For organizers',
  organizerBlurb:
    'One organizer hub for tiers, sell-through, promos, and door check-in. Launch new drops from inside — no duplicate nav.',
  liveBoardHint: 'Ranked by demand, capacity, and what is moving right now',
  homeHeadline: 'Get in before the room sells out',
  homeSubhead:
    'Live drops, fast checkout, and a wallet pass at the door. No account wall — just find the room and move.',
  homeSellingNow: 'Selling now',
  homeBrowseAll: 'Browse all drops',
  homeHowItWorksTitle: 'How it works',
  homeHowItWorksSteps: [
    { title: 'Find a drop', body: 'Browse live rooms and see real fill rate before you commit.' },
    { title: 'Checkout in seconds', body: 'Guest email, a short hold timer, then pay — no signup wall.' },
    { title: 'Show your pass', body: 'Rotating QR in your wallet when you walk up to the door.' },
  ] as const,
  homeAcceptsTitle: 'What Turnstile supports',
  homeAcceptsPayments: 'Payments',
  homeAcceptsPaymentsBody: 'Stripe checkout — Apple Pay, Google Pay, and major cards where supported.',
  homeAcceptsBuying: 'Buying',
  homeAcceptsBuyingBody: 'Guest checkout by default. No account required to grab tickets.',
  homeAcceptsEvents: 'Events',
  homeAcceptsEventsBody: 'Drop-style live sales — clubs, live shows, and limited-capacity tiers.',
  homeAcceptsTrust: 'Built in',
  homeAcceptsTrustBody: 'Live sell-through, waitlists, promo codes, and door scanning.',
  homeBuyerStrip: [
    { title: 'Upfront pricing', body: 'See tier prices and fees before you hold — no surprises at checkout.' },
    { title: 'Wallet-ready passes', body: 'Tickets land in your wallet with a rotating QR for door check-in.' },
    { title: 'Real demand', body: 'Live fill bars so you know when a room is about to sell out.' },
  ] as const,
  homeOrganizerTitle: 'Running a room?',
  homeOrganizerSubhead: 'Launch drops, track fill rate, and scan at the door — all from your organizer hub.',
  statLiveDrops: 'Live drops',
  statTicketsMoved: 'Tickets moved',
  statAvgFill: 'Avg fill',
  statCities: 'Cities',
  statOnSaleNow: 'On sale now',
  statActiveDrops: 'Active drops',
  statSellThrough: 'Sell-through',
  statMarkets: 'Markets',
  tableDrop: 'Drop',
  tableFill: 'Fill',
  tableFrom: 'From',
  tableStatus: 'Status',
  tableAction: 'Action',
  noDropsLive: 'No drops live yet',
  noDropsLiveHint: 'Be the first to launch a room.',
  loadDropsFailed: 'The live board is resting',
  loadDropsFailedHint:
    'The drop feed could not reach the database. The room is still here — retry in a moment or keep browsing the static surfaces.',
  firstDropHint: 'Launch your first drop — open tiers and watch fill rate move.',
  dropDetails: 'Drop details',
  guestList: 'Guest list',
  setupBrand: 'Set up your brand',
  setupBrandHint: 'Name and profile for your organizer hub.',
  saveBrandProfile: 'Save brand profile',
  pickPoster: 'Pick a poster',
  firstTier: 'First tier',
  readyToLaunch: 'Ready to launch',
  ticketTiers: 'Ticket tiers',
  salesByTier: 'Sales by tier',
  promoCodes: 'Promo codes',
  backToWallet: 'Back to wallet',
  qrRefresh: 'Rotating QR · refreshes every 25s',
  scanNoEvent: 'Pick a drop in your organizer hub to start scanning',
  scanHideSearch: 'Hide search',
  eventsPageDesc: 'Live drops, upcoming rooms, and sellout campaigns',
  waitlistEmail: 'Email for waitlist',
  shareDropTitle: (title: string) => `${title} · Turnstile`,
  fromPrice: (price: string) => `from ${price}`,
} as const

export const HOME_BUYER_FEATURES = COPY.homeBuyerStrip

export const HOME_FEATURES = HOME_BUYER_FEATURES

export const NAV_QUICK_LINKS = [
  { label: COPY.liveDropsLink, href: '/events' },
  { label: COPY.organizers, href: '/organizers' },
  { label: COPY.myWallet, href: '/wallet' },
  { label: COPY.doorScanner, href: '/scan' },
] as const

export const GENERIC_BLOCKED = [
  'Create event',
  'View dashboard',
  'Manage tickets',
  'Discover events',
  'Browse events',
  'Get Started',
  'Dashboard',
  'Event details',
  'Event organizer',
] as const
